sudo: required

services:
  - docker

before_install:
  # Create the virtual env and lint the codebase
  - make lint VENV_EXTRA_ARGS="--system-site-packages"
  # # Install the coverage utility and codecov reporting utility
  # - python -m pip install codecov
script:
  # This is the same as `python setup.py test` with a coverage wrapper.
  - make test
# XXX We'll bring this back later...
# after_success:
#   # Report test coverage to codecov.io
#   - codecov
notifications:
  email: false
