version: '2'
services:
  app:
    build: .
    volumes:
      - ./docs:/app/docs:z
      - ./press:/app/press:z
      - ./tests:/app/tests:z
      - ./htmlcov:/app/htmlcov:z
  web:
    extends:
      service: app
    command: gunicorn -b 0.0.0.0:6543 -n press --reload press.wsgi:app
    ports:
      - "80:6543"
