version: '2'
# If you have modifications, put those in docker-compose.override.yml
# See also, https://docs.docker.com/compose/extends/#multiple-compose-files
services:
  # Our services:
  app:
    build: .
    volumes:
      - ./docs:/app/docs:z
      - ./press:/app/press:z
      - ./tests:/app/tests:z
      - ./htmlcov:/app/htmlcov:z
      - ./var:/app/var:z
    environment:
      - SHARED_DIR=/app/var
  web:
    extends:
      service: app
    command: gunicorn -b 0.0.0.0:6543 -n press --reload wsgi:app
    ports:
      - "80:6543"
