version: '2'
services:
  # Our services:
  app:
    build: .
    volumes:
      - ./docs:/app/docs:z
      - ./press:/app/press:z
      - ./tests:/app/tests:z
      - ./htmlcov:/app/htmlcov:z
      - ./var:/app/var:z
    environment:
      - SHARED_DIR=/app/var
  web:
    extends:
      service: app
    command: gunicorn -b 0.0.0.0:6543 -n press --reload press.wsgi:app
    ports:
      - "80:6543"
